{
 "title": "envsensor.net",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "SELECT DISTINCT toString(topic) AS topic FROM envsensor.readings ORDER BY topic"
   }
  ]
 },
 "panels": [
  {
   "title": "last measurement time ('Europe/Budapest' timezone)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT formatDateTime(max(time), '%F %T', 'Europe/Budapest') AS max_time\nFROM envsensor.readings\nWHERE topic = ${topic:sqlstring};"
    }
   ]
  },
  {
   "title": "last measurements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bme280_t, sht4x_t, bme280_h, sht4x_h, bme280_p, esp32_t, rssi\nFROM envsensor.readings\nWHERE topic = ${topic:sqlstring}\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "air temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT time, bme280_t, sht4x_t, (bme280_t + sht4x_t) / 2 AS avg_t\nFROM envsensor.readings\nWHERE time >= $__fromTime AND time <= $__toTime\n  AND topic = ${topic:sqlstring}\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "air humidity (RH%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT time, bme280_h, sht4x_h, (bme280_h + sht4x_h) / 2 AS avg_h\nFROM envsensor.readings\nWHERE time >= $__fromTime AND time <= $__toTime\n  AND topic = ${topic:sqlstring}\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "atmospheric pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, bme280_p\nFROM envsensor.readings\nWHERE time >= $__fromTime AND time <= $__toTime\n  AND topic = ${topic:sqlstring}\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "ESP32 chip temperature (℃)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT time, esp32_t\nFROM envsensor.readings\nWHERE time >= $__fromTime AND time <= $__toTime\n  AND topic = ${topic:sqlstring}\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "wi-fi RSSI (dBm)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time, rssi\nFROM envsensor.readings\nWHERE time >= $__fromTime AND time <= $__toTime\n  AND topic = ${topic:sqlstring}\nORDER BY time ASC;"
    }
   ]
  }
 ]
}