{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    {{- toYaml .config | nindent 4 }}
---
{{- end }}

