apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: kafka
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    version: {{ .Values.kafka.version }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    template:
      pod:
        nodeSelector:
          {{- toYaml .Values.kafka.nodeSelector | nindent 10 }}
        tolerations:
          {{- toYaml .Values.kafka.tolerations | nindent 10 }}
        affinity:
          {{- toYaml .Values.kafka.affinity | nindent 10 }}

  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
    template:
      pod:
        nodeSelector:
          {{- toYaml .Values.zookeeper.nodeSelector | nindent 10 }}
        affinity:
          {{- toYaml .Values.zookeeper.affinity | nindent 10 }}

  entityOperator:
    topicOperator: {}
    userOperator: {}

