apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.zookeeper.storage.class }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "{{ .Values.zookeeper.storage.replicationFactor }}"
  staleReplicaTimeout: "30"
  fromBackup: ""

