# Namespace to deploy to
namespace: kafka

# Kafka cluster
kafka:
  clusterName: kafka-cluster
  version: 3.9.0
  storage:
    size: 25Gi
    class: kafka-local
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
      authentication:
        type: scram-sha-512
  logging:
    type: inline
    loggers:
      log4j.logger.kafka: "INFO"
      log4j.logger.io.strimzi: "INFO"
      log4j.logger.org.apache.kafka: "INFO"

# KafkaNodePools for Brokers and Controllers
kafkaNodePools:
  - name: kafka-brokers
    replicas: 4
    roles:
      - broker
    storage:
      size: 25Gi
      class: kafka-local
    resources:
      requests:
        memory: 512Mi
        cpu: "1000m"
      limits:
        memory: 1200Mi
        cpu: "1800m"
    nodeSelector:
      node-role.kubernetes.io/kafka: "true"
    tolerations:
      - key: node-role.kubernetes.io/kafka
        operator: Exists
        effect: NoSchedule

  - name: kafka-controllers
    replicas: 3
    roles:
      - controller
    storage:
      size: 3Gi
      class: kafka-longhorn
    resources:
      requests:
        memory: 512Mi
        cpu: "500m"
      limits:
        memory: 1000Mi
        cpu: "1000m"
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    tolerations: []

# Kafka Controller Storage (Longhorn)
kafkaControllerStorage:
  class: kafka-longhorn
  size: 3Gi
  replicationFactor: 2
  staleReplicaTimeout: "30"
  fromBackup: ""

# Kafka users
users:
  - name: admin
    type: scram-sha-512
    roles: admin
  - name: producer
    type: scram-sha-512
    roles: producer
  - name: consumer
    type: scram-sha-512
    roles: consumer

# Kafka topics auto-creation
topics:
  - name: example-topic
    partitions: 3
    replicas: 3
    config:
      retention.ms: 604800000  # Retain messages for 7 days
      segment.bytes: 1073741824
  - name: logs
    partitions: 5
    replicas: 3
    config:
      retention.ms: 1209600000  # Retain messages for 14 days
      cleanup.policy: "delete"
  - name: metrics
    partitions: 2
    replicas: 2
    config:
      retention.ms: 259200000  # Retain messages for 3 days
      segment.bytes: 524288000  # 500MB segments

