# StorageClass configuration for Kafka local storage
storageClass:
  name: kafka-local
  volumeBindingMode: WaitForFirstConsumer

# PVC size per Kafka broker: 45Gi
# To avoid filesystem overhead issues on 50Gi `/dev/sda2` XFS volumes
persistentVolumeSize: 45Gi

# PersistentVolumes definitions for each Kafka node
persistentVolumes:
  - name: worker1-pv
    node: worker1
    path: /var/lib/kafka
  - name: worker2-pv
    node: worker2
    path: /var/lib/kafka
  - name: worker3-pv
    node: worker3
    path: /var/lib/kafka
  - name: worker4-pv
    node: worker4
    path: /var/lib/kafka
